### ISSUE TITLE
你的mvc5下载下来后。编译的时候。总是提示还原什么失败！！！

### ISSUE THREAD

**Issue by diandian71** [shiningrise/Plugin#1]
还有就是从nuget上下载的dll。不知道怎么使用。按照你mvc4的方式来使用。貌似不行。请指教！！！

**Comment by shiningrise** [comment]
我还在debug，你迟点吧

**Comment by shiningrise** [comment]
你现在下载github的程序试试

**Comment by shiningrise** [comment]
我的环境是vs2013+update4,如果还不能正常编译运行，而且排除nuget还原原因，就升级一下环境再试试
nuget源上的还没更新
